version: "3"

services:
    accessibilite:
      build:
        context: .
        dockerfile: Dockerfile
      restart: on-failure

      ports:
        - "3000:3000"
      volumes:
        - .:/usr/accessibilite
        - "/usr/accessibilite/node_modules"

    db:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: database
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "3306:3306"

volumes:
  db_data:
